### PR TITLE
feat: skipping files based on regex and fixing parsing of args

### LINKED ISSUE #81: Arguments are not parsed if path is specified
When I run
```bash
./renpy-graphviz . -silent -open=false
```
the program still outputs something and opens. It's because of how https://pkg.go.dev/flag works, when it encounters any non-flag in the arguments, it stops parsing everything.
See the run in empty directory:
```bash
./renpy-graphviz . -silent -open=false
digraph  {


}
```
and it opens the empty image.
The same behavior as 
```bash
./renpy-graphviz .
digraph  {


}
```
would do.
It does not happen when no path is passed.
```bash
./renpy-graphviz -silent -open=false
```

### PR DESCRIPTION
**Pull request by racinmat**
This PR fixes #81 and adds a new flag which lets you skip some files based on regex. Sometimes people keep testing files in the game and I don't want to delete them when running the code, I want to skip them by passing some argument to the program 
There are multiple ways to do it, but I feel like using regex is the simplest, because you can skip arbitrary amount of files just by passing single regex.

And regarding the boolean flags, the only way how to pass them false value is using `=`, which is non-intuitive, so I added example to the readme. See the docs: https://pkg.go.dev/flag which say `-flag x  // non-boolean flags only`

I have tested it locally and it works well.

### CODE REVIEW

File: cli.go [hunk 1]
```diff
@@ -55,19 +62,25 @@ func PlugCLI() (string, parser.RenpyGraphOptions) {
...
-		path = flag.Args()[0]
+	// Manually handle the non-flag argument
+	var path string
+	if len(os.Args) > 1 && !isFlag(os.Args[1]) {
+		path = os.Args[1]
+		os.Args = append(os.Args[:1], os.Args[2:]...) // Remove the non-flag argument from os.Args
+	} else {
+		path = "."
 	}
+	flag.Parse()
```
Comment (EwenQuim) [inline cli.go:75]: `flag.Parse()` does it too, why are you doing it manually?

**Review by EwenQuim — COMMENTED** [review]
Thanks for your PR!

File: cli.go (hunk 1 above)
Comment (racinmat) [reply cli.go:75]: Because if it already did that, the bug would not be happening in a first place, so because the bug occurs with just calling flag.Parse and does not occur after this path extraction, it means the flag.Parse does not do it on it's own. It actually skips the arg, because it recognizes only named arguments and skips the rest.

**Review by EwenQuim — APPROVED** [review]
